# Generated by Django 4.2.21 on 2025-05-25 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manager_auth', '0002_hospitaluser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaluser',
            name='direct_id',
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
